name: PR Notification to Teams

on:
  pull_request:
    types: [opened, reopened]

jobs:
  notify:
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Send PR Notification to Power Automate
        shell: pwsh
        env:
          FLOW_WEBHOOK_URL: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
        run: |
          # Pull request information from GitHub Actions context
          $prTitle = "${{ github.event.pull_request.title }}"
          $prCreator = "${{ github.event.pull_request.user.login }}"
          $prUrl = "${{ github.event.pull_request.html_url }}"

          # Compose the payload for Power Automate
          $payload = @{
              title   = $prTitle
              creator = $prCreator
              url     = $prUrl
          } | ConvertTo-Json -Depth 2

          # Send the payload to Power Automate
          try {
              Invoke-RestMethod -Method Post -Uri $env:FLOW_WEBHOOK_URL -Body $payload -ContentType 'application/json'
              Write-Output "Power Automate flow triggered successfully."
          }
          catch {
              Write-Error "Failed to trigger Power Automate flow. Error: $_"
          }
