name: PR Notification Email

on:
  pull_request:
    types: [opened, reopened]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Send email using Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install secure-smtplib email-validator

    - name: Send Email
      env:
        OUTLOOK_EMAIL: ${{ secrets.OUTLOOK_EMAIL }}
        OUTLOOK_PASSWORD: ${{ secrets.OUTLOOK_PASSWORD }}
      run: |
        python - <<EOF
        import smtplib
        from email.mime.text import MIMEText
        from email.mime.multipart import MIMEMultipart

        sender_email = "${{ secrets.OUTLOOK_EMAIL }}"
        password = "${{ secrets.OUTLOOK_PASSWORD }}"
        receiver_email = "${{ secrets.OUTLOOK_EMAIL }}"

        message = MIMEMultipart("alternative")
        message["Subject"] = "GitHub Actions Test Email"
        message["From"] = sender_email
        message["To"] = receiver_email

        text = "Hello, this is a test email sent via GitHub Actions using Outlook."
        html = "<html><body><p>Hello, this is a <b>test email</b> sent via GitHub Actions using Outlook.</p></body></html>"

        part1 = MIMEText(text, "plain")
        part2 = MIMEText(html, "html")

        message.attach(part1)
        message.attach(part2)

        with smtplib.SMTP("smtp.office365.com", 587) as server:
            server.starttls()
            server.login(sender_email, password)
            server.sendmail(sender_email, receiver_email, message.as_string())
            print("Email sent successfully!")
        EOF
