name: PR Notification to Teams

on:
  pull_request:
    types: [opened]

jobs:
  notify:
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Send Teams Notification
        shell: pwsh
        env:
          TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}
        run: |
          function Send-Notification {
              param(
                  [string]$WebhookURL,
                  [array]$messageParts
              )

              if ($null -ne $messageParts.Count -and $messageParts.Count -gt 0) {
                  $message = @{
                      'text'  = ($messageParts -join "<br /><br />")
                      'title' = "New Pull Request Notification"
                  }

                  $messageJson = $message | ConvertTo-Json -Depth 2

                  try {
                      Invoke-RestMethod -Method Post -Uri $WebhookURL -Body $messageJson -ContentType 'application/json'
                      Write-Output "Notification sent successfully."
                  }
                  catch {
                      Write-Error "Failed to send Teams notification. Error: $_"
                  }
              }
          }

          # Pull request information from GitHub Actions context
          $prTitle = "${{ github.event.pull_request.title }}"
          $prCreator = "${{ github.event.pull_request.user.login }}"
          $prUrl = "${{ github.event.pull_request.html_url }}"

          # Compose the message
          $messageParts = @(
              "There was a new pull request made by **$prCreator** that needs to be reviewed.",
              "The pull request can be found here: $prUrl"
          )

          # Send the notification
          Send-Notification -WebhookURL $env:TEAMS_WEBHOOK_URL -messageParts $messageParts
