name: PR Notification to Teams

on:
  pull_request:
    types: [opened, reopened]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Send PR notification to Teams via Power Automate
        run: |
          curl -X POST ${{ secrets.MS_TEAMS_WEBHOOK_URI }} \
            -H "Content-Type: application/json" \
            -d '{
              "title": "New Pull Request Created",
              "url": "${{ github.event.pull_request.html_url }}",
              "author": "${{ github.event.pull_request.user.login }}",
              "repo": "${{ github.repository }}"
            }'
