name: PR Notification Email

on:
  pull_request:
    types: [opened, reopened]

jobs:
  notify:
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Send PR Email via SMTP
        shell: pwsh
        env:
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}     
          SMTP_PORT: ${{ secrets.SMTP_PORT }}          
          SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}   
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}   
          EMAIL_TO: ${{ secrets.EMAIL_TO }}             
        run: |
          # Pull request info
          $prTitle = "${{ github.event.pull_request.title }}"
          $prCreator = "${{ github.event.pull_request.user.login }}"
          $prUrl = "${{ github.event.pull_request.html_url }}"

          # Email content
          $subject = "New pull request - $prTitle"
          $body = @"
          There was a new pull request created by $prCreator which needs to be reviewed.
          The pull request can be found here: $prUrl
          "@

          # Send email
          try {
              Send-MailMessage `
                  -SmtpServer $env:SMTP_SERVER `
                  -Port $env:SMTP_PORT `
                  -UseSsl `
                  -Credential (New-Object System.Management.Automation.PSCredential($env:SMTP_USERNAME, (ConvertTo-SecureString $env:SMTP_PASSWORD -AsPlainText -Force))) `
                  -From $env:SMTP_USERNAME `
                  -To $env:EMAIL_TO `
                  -Subject $subject `
                  -Body $body
              Write-Output "Email sent successfully."
          }
          catch {
              Write-Error "Failed to send email. Error: $_"
          }
