name: PR Notification to Teams

on:
  pull_request:
    types: [opened, reopened]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get OAuth token
        id: get_token
        run: |
          response=$(curl -X POST "https://login.microsoftonline.com/${{ secrets.AZURE_TENANT_ID }}/oauth2/v2.0/token" \
            -H "Content-Type: application/x-www-form-urlencoded" \
            -d "client_id=${{ secrets.AZURE_CLIENT_ID }}" \
            -d "scope=https://graph.microsoft.com/.default" \
            -d "client_secret=${{ secrets.AZURE_CLIENT_SECRET }}" \
            -d "grant_type=client_credentials")
          echo "ACCESS_TOKEN=$(echo $response | jq -r '.access_token')" >> $GITHUB_ENV

      - name: Send PR notification to Teams via Power Automate
        run: |
          curl -X POST ${{ secrets.MS_TEAMS_WEBHOOK_URI }} \
            -H "Authorization: Bearer $ACCESS_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{
              "title": "New Pull Request Created",
              "url": "${{ github.event.pull_request.html_url }}",
              "author": "${{ github.event.pull_request.user.login }}",
              "repo": "${{ github.repository }}"
            }'
