name: PR Notification Email

on:
  pull_request:
    types: [opened, reopened]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Send Email
      uses: dawidd6/action-send-mail@v6
      with:
        server_address: smtp.office365.com
        server_port: 587
        username: ${{ secrets.OUTLOOK_EMAIL }}
        password: ${{ secrets.OUTLOOK_PASSWORD }}
        subject: "New Pull Request: ${{ github.event.pull_request.title }}"
        body: |
          <h1>New pull request - ${{ github.event.pull_request.title }}</h1>
          <p>There is a new pull request made by <b>${{ github.event.pull_request.user.login }}</b> that needs to be reviewed.</p>
          <p>The pull request can be found <a href="${{ github.event.pull_request.html_url }}">here</a>.</p>
        to: ${{ secrets.OUTLOOK_EMAIL }}
        from: ${{ secrets.OUTLOOK_EMAIL }}
        secure: true
        html: true
